### ISSUE TITLE
Authenticating with OpenID-Connect

### ISSUE THREAD

**Issue by paulmillar** [CyberDem0n/pam-oauth2#6]
Hi,

I'm interested in understanding whether this PAM module might be used with an OpenID-Connect provider, since OIDC is based on OAuth2.  I believe this doesn't work right now, but the two discrepancies I've found might be fairly easily fixed.

(This issue is really to test the water, to see whether OIDC access-token support is of interest.  The individual issues could be split off into separate issues, if that would help in managing them.)

First issue: embedding the access-token in URL query part.

An OIDC user-info endpoint is authorised by the access token:

https://openid.net/specs/openid-connect-core-1_0.html#UserInfoRequest

This is done using the `Authorization` request header.  This PAM module currently seems to embed the access token within the userinfo endpoint's URL, as a query parameter.

Would it be possible to add support for querying the OP's userinfo endpoint using the Authorization request header?

Second issue: the PAM module seems to assume that the OP returns at least the username (and also group-membership?) in the user-info endpoint response.

A successful OIDC userinfo response can contain many claims:

https://openid.net/specs/openid-connect-core-1_0.html#UserInfoResponse

However, I believe the only guaranteed one is `sub`, which uniquely identifies the individual.  More generally, there are OPs that identify many individuals: users (of the the machine) and other people who have no account on this machine.

Therefore, some library/component/configuration-file would be needed that maps `sub` claim values to the corresponding users on the system.  This PAM module would also need to reject login requests that are valid, but for which there is no mapped user.

Do you have any thoughts on how this mapping might be achieved? 

Finally, it would be helpful if you could provide some worked examples, showing a PAM configuration and an application/service where the user may be logged in when they provide an access token.

Cheers,
Paul.

**Comment by CyberDem0n** [comment]
Hi @paulmillar,

I did this library a few years ago as a quick hack to enable single sign-on to PostgreSQL cluster which we run at Zalando.
It does everything we want therefore I don't really have spare time (or interest) for further development.

Feel free to fork it and implement everything you need. There are already quite a few forks out there: https://github.com/CyberDem0n/pam-oauth2/network

**Comment by paulmillar** [comment]
Hi @CyberDem0n,

Thanks for the quick reply.

What you say certainly makes sense.

I see the EUDAT fork seems to do pretty much what I would like, plus I know the guys, so I'll give that version a go.

Cheers,
Paul.
