### ISSUE TITLE
Authtok cut at 1024 characters

### ISSUE THREAD

**Issue by webD97** [CyberDem0n/pam-oauth2#9]
Hello, first of all: Thank you for your work on this project.

I'm still learning PAM and have been experimenting with this module for a few hours now. Unfortunately I am not able to get it working. Maybe I am misunderstanding something and you can point in the right direction.

I set up the module in the PAM config and placed it above pam_localuser.so. I can see from the logs that the module is working but I keet getting 4xx errors from my Keycloak instance. I added some more syslog calls and found that the access_token I pass during login is incomplete: strlen reports that it has 1023 characters while the one I pass during login has 1555 characters. Therefore Keycloak fails during the request to the info endpoint.

I did my tests using SSH and thought I'm supposed to pass the token where I normally enter a password. Is that my mistake? 

Thanks for your help :)

**Comment by CyberDem0n** [comment]
> I did my tests using SSH and thought I'm supposed to pass the token where I normally enter a password. Is that my mistake?

I never tried to use it with SSH. Our original goal was authenticating in PostgreSQL with tokens instead of passwords.
But! I can tell for sure that for example PostgreSQL default console client `psql` gets only the first 100 characters from the password prompt. I wonder if SSH does something similar.

**Comment by webD97** [comment]
I'll dig into this and share my results. Thanks for the idea!

**Comment by webD97** [comment]
OpenSSH seems to enforce a hardcoded maximum password length: https://github.com/openssh/openssh-portable/blob/master/auth-passwd.c#L70

**Comment by webD97** [comment]
Since it looks like we are not able to do something against this issue here, I will close it.
